#pragma once

// =============================================================================
//  motor/tracking.h  —  TMC2209 polar axis tracking motor
//
//  Responsibilities:
//    1. Configure TMC2209 via UART on startup (current, microstepping, etc.)
//    2. Manage the GPTimer sidereal step ISR (via hal/gptimer.h)
//    3. Expose rate and correction controls to the state machine
//
//  The actual step pulse is generated by the ISR in hal/gptimer.c.
//  This module is the higher-level policy layer above that.
// =============================================================================

#include <stdbool.h>
#include <stdint.h>
#include "hal/gptimer.h"    // for track_rate_t

// Initialise TMC2209 over UART (sets current, microstepping, stealthChop).
// Must be called before tracking_start().
// Returns false if TMC2209 does not respond (wiring/power fault).
bool tracking_init(void);

// Start/stop the sidereal tracking ISR.
// These are called by the state machine on entering/leaving STATE_TRACKING.
void tracking_start(void);
void tracking_stop(void);

// Change the tracking rate (sidereal / lunar / solar).
// Takes effect immediately without stopping the motor.
void tracking_set_rate(track_rate_t rate);

// Apply closed-loop correction from the dual IMU feedback.
// error_arcsec: from imu_get_tracking_error_arcsec()
//   Positive error → camera is ahead → slow down slightly
//   Negative error → camera is behind → speed up slightly
// Call this at ~10 Hz from the state machine tick while tracking.
void tracking_apply_imu_correction(double error_arcsec);

// Direction reversal — normally tracks eastward, set to reverse for
// southern hemisphere operation (polar axis pointing at south pole).
void tracking_set_direction_reversed(bool reversed);

// TMC2209 status — read back from chip via UART
typedef struct {
    uint16_t driver_status;     // raw DRV_STATUS register
    bool     stall_detected;    // SG_RESULT below threshold
    bool     overtemp_warning;
    bool     overtemp_shutdown;
    bool     open_load_a;
    bool     open_load_b;
    float    estimated_load;    // 0.0–1.0, from StallGuard
} tmc2209_status_t;

// Read TMC2209 status. Useful for the LoRa telemetry packet.
tmc2209_status_t tracking_get_motor_status(void);
