M48
; DRILL file {KiCad 9.0.8-1.fc43} date 2026-03-28T20:24:26+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-28T20:24:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-1.fc43
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X6.5334Y-4.8814
X6.761Y-4.8814
T2
X6.8574Y-2.0825
X6.8574Y-2.3581
M30
