[env:esp32-s3-wroom-2-n32r16v]
platform = espressif32@6.8.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
board_build.partitions = default.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
